import "./globals.css";

import AuthContext from "./authContext";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <AuthContext>
      <html lang="en">
        <body>{children}</body>
      </html>
    </AuthContext>
  );
}
